name: Hprofile Actions
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: actions/checkout@v4

      - name: Maven Testing
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
